//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderLine = new HashSet<OrderLine>();
        }
    
        public long orderId { get; set; }
        public System.DateTime purchasingDate { get; set; }
        public string name { get; set; }
        public decimal totalPrice { get; set; }
        public long cardId { get; set; }
        public long userId { get; set; }
        public string address { get; set; }
        public bool expressShipping { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK__Order__cardId__34C8D9D1
        /// </summary>
        public virtual BankCard BankCard { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK__Order__userId__35BCFE0A
        /// </summary>
        public virtual User User { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK__OrderLine__order__38996AB5
        /// </summary>
        public virtual ICollection<OrderLine> OrderLine { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + purchasingDate.GetHashCode();
    			hash = hash * multiplier + (name == null ? 0 : name.GetHashCode());
    			hash = hash * multiplier + totalPrice.GetHashCode();
    			hash = hash * multiplier + cardId.GetHashCode();
    			hash = hash * multiplier + userId.GetHashCode();
    			hash = hash * multiplier + (address == null ? 0 : address.GetHashCode());
    			hash = hash * multiplier + expressShipping.GetHashCode();
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object? 
    
            Order target = obj as Order;
    
    		return true
               &&  (this.orderId == target.orderId )       
               &&  (this.purchasingDate == target.purchasingDate )       
               &&  (this.name == target.name )       
               &&  (this.totalPrice == target.totalPrice )       
               &&  (this.cardId == target.cardId )       
               &&  (this.userId == target.userId )       
               &&  (this.address == target.address )       
               &&  (this.expressShipping == target.expressShipping )       
               ;
    
        }
    
    
    	public static bool operator ==(Order  objA, Order  objB)
        {
            // Check if the objets are the same Order entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(Order  objA, Order  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strOrder = new StringBuilder();
    
    		strOrder.Append("[ ");
           strOrder.Append(" orderId = " + orderId + " | " );       
           strOrder.Append(" purchasingDate = " + purchasingDate + " | " );       
           strOrder.Append(" name = " + name + " | " );       
           strOrder.Append(" totalPrice = " + totalPrice + " | " );       
           strOrder.Append(" cardId = " + cardId + " | " );       
           strOrder.Append(" userId = " + userId + " | " );       
           strOrder.Append(" address = " + address + " | " );       
           strOrder.Append(" expressShipping = " + expressShipping + " | " );       
            strOrder.Append("] ");    
    
    		return strOrder.ToString();
        }
    
    
    }
}
