//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Comment = new HashSet<Comment>();
            this.OrderLine = new HashSet<OrderLine>();
            this.SpecificProperty = new HashSet<SpecificProperty>();
        }
    
        public long productId { get; set; }
        public string name { get; set; }
        public double price { get; set; }
        public System.DateTime addingDate { get; set; }
        public int stock { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public Nullable<long> categoryId { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK__Product__categor__276EDEB3
        /// </summary>
        public virtual Category Category { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK__Comment__product__3C69FB99
        /// </summary>
        public virtual ICollection<Comment> Comment { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK__OrderLine__produ__398D8EEE
        /// </summary>
        public virtual ICollection<OrderLine> OrderLine { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK__SpecificP__produ__2A4B4B5E
        /// </summary>
        public virtual ICollection<SpecificProperty> SpecificProperty { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + (name == null ? 0 : name.GetHashCode());
    			hash = hash * multiplier + price.GetHashCode();
    			hash = hash * multiplier + addingDate.GetHashCode();
    			hash = hash * multiplier + stock.GetHashCode();
    			hash = hash * multiplier + (image == null ? 0 : image.GetHashCode());
    			hash = hash * multiplier + (description == null ? 0 : description.GetHashCode());
    			hash = hash * multiplier + (categoryId == null ? 0 : categoryId.GetHashCode());
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object? 
    
            Product target = obj as Product;
    
    		return true
               &&  (this.productId == target.productId )       
               &&  (this.name == target.name )       
               &&  (this.price == target.price )       
               &&  (this.addingDate == target.addingDate )       
               &&  (this.stock == target.stock )       
               &&  (this.image == target.image )       
               &&  (this.description == target.description )       
               &&  (this.categoryId == target.categoryId )       
               ;
    
        }
    
    
    	public static bool operator ==(Product  objA, Product  objB)
        {
            // Check if the objets are the same Product entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(Product  objA, Product  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strProduct = new StringBuilder();
    
    		strProduct.Append("[ ");
           strProduct.Append(" productId = " + productId + " | " );       
           strProduct.Append(" name = " + name + " | " );       
           strProduct.Append(" price = " + price + " | " );       
           strProduct.Append(" addingDate = " + addingDate + " | " );       
           strProduct.Append(" stock = " + stock + " | " );       
           strProduct.Append(" image = " + image + " | " );       
           strProduct.Append(" description = " + description + " | " );       
           strProduct.Append(" categoryId = " + categoryId + " | " );       
            strProduct.Append("] ");    
    
    		return strProduct.ToString();
        }
    
    
    }
}
